export{}
const mongoose = require("mongoose");

const Schema = mongoose.Schema;

const postSchema = new Schema({
    username: {type: String, minlength: 3, trim: true},
    filename: {type: String},
    imageId: {type: String},
    description: {type: String},
    likes: {type: Number},
    date: {type: Date}
},

//timestamps offer an autogenerated timestamp (createAt)
{timestamps: true,})

const Post = mongoose.model("Post", postSchema);

module.exports = Post;